services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODE=${MODE:-dev}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${MODE:-dev}
      - PORT=${PORT:-3000}
      - REACT_APP_API_HOST=${API_HOST:-localhost}
      - REACT_APP_API_PORT=${API_PORT:-3001}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:3000}
    image: frontend-tavola-italiana:v1.0.0
    container_name: frontend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command:
      - sh
      - -c
      - 'if [ "$NODE_ENV" = "prod" ]; then yarn build && yarn global add serve && serve -s build -l ${PORT:-3000}; else yarn start; fi'
